create table if not exists public.newsletter_signups (
  id bigint generated by default as identity primary key,
  email text not null,
  source text not null default 'homepage',
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists newsletter_signups_email_key
  on public.newsletter_signups (email);

alter table public.newsletter_signups enable row level security;

grant insert on table public.newsletter_signups to anon, authenticated;

drop policy if exists "Allow public newsletter inserts"
  on public.newsletter_signups;

create policy "Allow public newsletter inserts"
  on public.newsletter_signups
  for insert
  to anon, authenticated
  with check (
    email is not null
    and source = 'homepage'
  );
